spring.application.name=be-movies
#spring.data.mongodb.database=${env.MONGO_DATABASE}
#spring.data.mongodb.uri=mongodb+srv://${env.MONGO_USER}:${env.MONGO_PASSWORD}@${env.MONGO_CLUSTER}

spring.data.mongodb.database=movie-api-db
spring.data.mongodb.uri=mongodb+srv://yustanzah:Dewakematian27*@cluster0.ymlvdti.mongodb.net
